import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./provider";
import { supabaseServer } from "@/utils/supabase/server";
import HydrateUser from "@/components/HydrateUser";

export const metadata: Metadata = {
  title: "Bento Chat",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = await supabaseServer();

  const {
    data: { user },
  } = await supabase.auth.getUser();


  let profile = null;

  if (user) {
    const { data } = await supabase
      .from("User")
      .select("*")
      .eq("id", user.id)
      .single();

    profile = data;
    console.log("profile", profile)
  }

  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <HydrateUser profile={profile}>
            {children}
          </HydrateUser>

          <div id="modal-root" />
        </ReduxProvider>
      </body>
    </html>
  );
}

